
Microsoft Visual Studio Solution File, Format Version 12.00
Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "Dockerfile-Builder", "Dockerfile-Builder\Dockerfile-Builder.csproj", "{9C8C1AEF-623B-4130-8A19-0CBCBE85659E}"
EndProject
Global
	GlobalSection(SolutionConfigurationPlatforms) = preSolution
		Debug|Any CPU = Debug|Any CPU
		Release|Any CPU = Release|Any CPU
	EndGlobalSection
	GlobalSection(ProjectConfigurationPlatforms) = postSolution
		{9C8C1AEF-623B-4130-8A19-0CBCBE85659E}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
		{9C8C1AEF-623B-4130-8A19-0CBCBE85659E}.Debug|Any CPU.Build.0 = Debug|Any CPU
		{9C8C1AEF-623B-4130-8A19-0CBCBE85659E}.Release|Any CPU.ActiveCfg = Release|Any CPU
		{9C8C1AEF-623B-4130-8A19-0CBCBE85659E}.Release|Any CPU.Build.0 = Release|Any CPU
	EndGlobalSection
EndGlobal
